//! Built-in copy sounds, generated by `scripts/gen-sounds.mjs`.

pub const NAMES: [&str; 5] = ["pop", "click", "chime", "bubble", "tap"];

pub fn wav(name: &str) -> Option<&'static [u8]> {
    Some(match name {
        "pop" => include_bytes!("../sounds/pop.wav"),
        "click" => include_bytes!("../sounds/click.wav"),
        "chime" => include_bytes!("../sounds/chime.wav"),
        "bubble" => include_bytes!("../sounds/bubble.wav"),
        "tap" => include_bytes!("../sounds/tap.wav"),
        _ => return None,
    })
}

/// Plays a built-in sound. Main thread only on macOS (AppKit).
#[cfg(target_os = "macos")]
pub fn play(name: &str) {
    use objc2::{AnyThread, rc::Retained};
    use objc2_app_kit::NSSound;
    use objc2_foundation::NSData;
    use std::{cell::RefCell, collections::HashMap};

    // Keep each NSSound alive so playback isn't cut off when it would be dropped.
    thread_local! {
        static LOADED: RefCell<HashMap<String, Retained<NSSound>>> = RefCell::default();
    }
    let Some(bytes) = wav(name) else { return };
    LOADED.with_borrow_mut(|loaded| {
        if !loaded.contains_key(name) {
            let Some(sound) = NSSound::initWithData(NSSound::alloc(), &NSData::with_bytes(bytes)) else { return };
            loaded.insert(name.to_string(), sound);
        }
        let sound = &loaded[name];
        // Restart if a previous copy's sound is still playing.
        sound.stop();
        sound.play();
    });
}

#[cfg(windows)]
pub fn play(name: &str) {
    use ::windows::Win32::Media::Audio::{PlaySoundW, SND_ASYNC, SND_MEMORY};
    use ::windows::core::PCWSTR;
    if let Some(bytes) = wav(name) {
        // With SND_MEMORY the "file name" is the whole WAV image, which is 'static here.
        let _ = unsafe { PlaySoundW(PCWSTR(bytes.as_ptr().cast()), None, SND_MEMORY | SND_ASYNC) };
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_sound_is_a_wav() {
        for name in NAMES {
            let bytes = wav(name).unwrap_or_else(|| panic!("{name} has no data"));
            assert_eq!(&bytes[0..4], b"RIFF", "{name}");
            assert_eq!(&bytes[8..12], b"WAVE", "{name}");
        }
        assert!(wav("loud").is_none());
    }
}
